version: '3'
services:

  nginx-stack.com:
    image: nginx
    container_name: nginx-stack
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www/index.html:/var/www/html/index.html:ro
    ports:
      - ${APP_PORT:-80}:80